### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by sscs12345** [skyrim/qmxx#2]
//// q_jumpstats.sma
// C:\Users\ss1234\Downloads\amxmodx-1.8.2-base-windows\addons\amxmodx\scripting\q_jumpstats.sma(1005) : error 017: undefined symbol "q_message_SayText"
//
// 1 Error.
// Could not locate output file C:\Users\ss1234\Downloads\amxmodx-1.8.2-base-windows\addons\amxmodx\scripting\compiled\q_jumpstats.amx (compile failed).
//
// Compilation Time: 0.41 sec
// ----------------------------------------

Press enter to exit ...

**Comment by skyrim** [comment]
Fixed in 86f17a7f22d6903d449258a5a0fe1f10e8d7b70a
Btw, I didn't receive any notifications from Github about issues on this project.
